name: Deploy website
on:
  push:
    branches:
      - job-artifacts-and-outputs
jobs:
  job__build:
    runs-on: ubuntu-latest
    steps:
      - name: "Step-01: Clone Repo"
        uses: actions/checkout@v3
      - name: "Step-02: Install dependencies"
        run: npm ci
      - name: "Step-03: Build website"
        run: npm run build
      - name: "Step-04: Upload the build artifacts present in the `dist` folder to a named `uploaded-build-artifacts` folder"
        uses: actions/upload-artifact@v3
        with:
          name: uploaded-build-artifacts #You can use this name to access the build artifacts in the further jobs
          path: dist #Map the folder name where the build artifacts would be generated when npm runbuild is triggered.
  

      # Suppose if you want to collect  { build artifacts + package.json + package-lock.json } into a folder named 'FILE_COLLECTIONS' then you need to do as below
      - name: "Step-05: collect { build artifacts + package.json + package-lock.json } into a folder named 'FILE_COLLECTIONS'"
        uses: actions/upload-artifact@v3
        with:
          name: FILE_COLLECTIONS
          path: |
            dist
            package.json
            package-lock.json


  job__deploy:
    needs: job__build
    runs-on: ubuntu-latest
    steps:
      - name: "Step-01: Download the artifacts from the `uploaded-build-artifacts` folder into a `downloaded-build-artifacts` folder"
        uses: actions/download-artifact@v3
        with:
          name: uploaded-build-artifacts
          path: downloaded-build-artifacts

      - name: "Step-02: List out the contents in the `downloaded-build-artifacts` folder"
        run: ls -R

      - name: "Step-03: Deploy"
        run: echo "Deploying..."
