name: Angular application deployment
on: workflow_dispatch
jobs:
    app-deployment:
        runs-on: windows-latest
        steps:
            - name: Clone the code
              uses: actions/checkout@v3
            - name: Install NodeJS
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: Install dependencies
              run: npm ci
            - name: Build the application
              run: npm run build 
